"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "english" | "hindi" | "punjabi" | "gujarati" | "marathi" | "telugu"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  english: {
    // Common
    welcome: "Welcome back, Rajesh!",
    farmStatus: "Here's what's happening with your farm today.",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    close: "Close",

    // Navigation
    dashboard: "Dashboard",
    cropDiagnosis: "Crop Diagnosis",
    marketAnalysis: "Market Analysis",
    governmentSchemes: "Government Schemes",
    expertConsultation: "Expert Consultation",
    community: "Community",
    agriNews: "Agri News",
    helpSupport: "Help & Support",
    profile: "Profile",
    settings: "Settings",
    notifications: "Notifications",
    logout: "Log out",

    // Voice Assistant
    voiceAssistant: "Voice Assistant",
    voiceDescription: "Speak in your native language - I'm here to help with all your farming needs",
    startSpeaking: "Start Speaking",
    listening: "Listening...",
    stopAudio: "Stop Audio",
    trySaying: "Try saying:",

    // Quick Actions
    quickActions: "Quick Actions",
    diagnoseCrop: "Diagnose Crop",
    checkPrices: "Check Prices",
    findSchemes: "Find Schemes",
    expertCall: "Expert Call",

    // Dashboard Stats
    farmSize: "Farm Size",
    cropsMonitored: "Crops Monitored",
    marketAlerts: "Market Alerts",
    schemesApplied: "Schemes Applied",
    recentActivity: "Recent Activity",

    // Crop Diagnosis
    cropDiseaseTitle: "Crop Disease Diagnosis",
    cropDiseaseDesc: "Use AI-powered image analysis to diagnose crop diseases and get treatment recommendations.",
    uploadPhoto: "Upload Photo",
    takePhoto: "Take Photo",
    analyzingImage: "Analyzing Image...",
    diagnosisResults: "Diagnosis Results",
    immediateeTreatment: "Immediate Treatment",
    localRemedies: "Local & Affordable Remedies",
    futurePrevention: "Future Prevention",
    recentDiagnoses: "Recent Diagnoses",
    photographyTips: "Photography Tips for Better Diagnosis",
    goodLighting: "Good Lighting",
    closeupShots: "Close-up Shots",
    multipleAngles: "Multiple Angles",
    cleanBackground: "Clean Background",

    // Market Analysis
    marketAnalysisTitle: "Market Analysis",
    marketAnalysisDesc:
      "Get real-time market prices and trends to make informed selling decisions for maximum profits.",
    selectCrop: "Select crop",
    selectMarket: "Select market",
    getLatestPrices: "Get Latest Prices",
    fetchingPrices: "Fetching Prices...",
    recommendation: "Recommendation:",
    marketSummary: "Market Summary",
    weeklyTrends: "Weekly Trends",
    marketTips: "Market Tips",
    bestSellingTimes: "Best Selling Times",
    qualityMatters: "Quality Matters",
    seasonalPatterns: "Seasonal Patterns",

    // Government Schemes
    governmentSchemesTitle: "Government Schemes Navigator",
    governmentSchemesDesc:
      "Discover and apply for government agricultural schemes and subsidies to support your farming operations.",
    yourAppliedSchemes: "Your Applied Schemes",
    trackStatus: "Track the status of your scheme applications",
    benefits: "Benefits",
    eligibility: "Eligibility",
    requiredDocuments: "Required Documents",
    deadline: "Deadline",
    applyNow: "Apply Now",
    applicationTips: "Application Tips",
    completeDocumentation: "Complete Documentation",
    meetDeadlines: "Meet Deadlines",
    verifyEligibility: "Verify Eligibility",
    followUp: "Follow Up",

    // Expert Consultation
    expertConsultationTitle: "Expert Consultation",
    expertConsultationDesc:
      "Connect with agricultural experts for personalized advice and solutions to your farming challenges.",
    upcomingConsultations: "Upcoming Consultations",
    availableExperts: "Available Experts",
    phoneConsultation: "Phone Consultation",
    videoConsultation: "Video Consultation",
    chatSupport: "Chat Support",
    instantExpertAdvice: "Instant expert advice",
    costEffectiveSolution: "Cost-effective solution",
    available24x7: "Available 24/7",
    visualCropAssessment: "Visual crop assessment",
    detailedExplanations: "Detailed explanations",
    screenSharingSupport: "Screen sharing support",
    sharePhotosDocuments: "Share photos & documents",
    writtenRecommendations: "Written recommendations",
    flexibleTiming: "Flexible timing",

    // Community
    farmerCommunity: "Farmer Community",
    communityDesc: "Connect with fellow farmers, share experiences, and learn from the community's collective wisdom.",
    newDiscussion: "New Discussion",
    recentDiscussions: "Recent Discussions",
    categories: "Categories",
    topContributors: "Top Contributors",
    communityStats: "Community Stats",
    totalMembers: "Total Members",
    activeDiscussions: "Active Discussions",
    questionsAnswered: "Questions Answered",
    onlineNow: "Online Now",

    // News
    agriculturalNews: "Agricultural News",
    newsDesc: "Stay updated with the latest news, weather alerts, market trends, and agricultural developments.",
    allNews: "All News",
    weatherAlerts: "Weather Alerts",
    marketUpdates: "Market Updates",
    governmentPolicy: "Government Policy",
    technology: "Technology",
    research: "Research",
    readMore: "Read More",
    weatherAlert: "Weather Alert",
    heavyRainfallWarning: "Heavy Rainfall Warning",
    stayUpdated: "Stay Updated",
    subscribeNewsletter: "Subscribe to Newsletter",

    // Help & Support
    helpSupportTitle: "Help & Support",
    helpDesc: "Find answers to common questions, access resources, and get support for using Project Kisan.",
    faq: "Frequently Asked Questions",
    contactSupport: "Contact Support",
    getHelp: "Get Help",
    phoneSupport: "Phone Support",
    emailSupport: "Email Support",
    liveChat: "Live Chat",
    helpResources: "Help Resources",
    gettingStartedGuide: "Getting Started Guide",
    videoTutorials: "Video Tutorials",
    featureDocumentation: "Feature Documentation",
    bestPractices: "Best Practices",
    systemStatus: "System Status",
    operational: "Operational",
    maintenance: "Maintenance",

    // Settings
    appearance: "Appearance",
    theme: "Theme",
    chooseTheme: "Choose your preferred theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    languageRegion: "Language & Region",
    language: "Language",
    chooseLanguage: "Choose your preferred language",
    region: "Region",
    setRegion: "Set your farming region",
    weatherAlertsSettings: "Weather Alerts",
    weatherAlertsDesc: "Get notified about weather changes",
    marketPriceUpdates: "Market Price Updates",
    marketPriceDesc: "Receive market price notifications",
    schemeAlerts: "Government Scheme Alerts",
    schemeAlertsDesc: "Stay updated on new schemes",
    diseaseWarnings: "Crop Disease Warnings",
    diseaseWarningsDesc: "Get alerts about crop diseases in your area",
    voiceResponse: "Voice Response",
    voiceResponseDesc: "Enable voice responses",
    voiceSpeed: "Voice Speed",
    voiceSpeedDesc: "Adjust voice response speed",
    slow: "Slow",
    normal: "Normal",
    fast: "Fast",
    privacyData: "Privacy & Data",
    dataCollection: "Data Collection",
    dataCollectionDesc: "Allow data collection for better recommendations",
    locationServices: "Location Services",
    locationServicesDesc: "Use location for weather and market data",
    saveSettings: "Save Settings",

    // Profile
    farmSizeProfile: "Farm Size",
    experience: "Experience",
    primaryCrops: "Primary Crops",
    contactInformation: "Contact Information",
    about: "About",
    saveChanges: "Save Changes",

    // Status and Actions
    active: "Active",
    applied: "Applied",
    completed: "Completed",
    healthy: "Healthy",
    treated: "Treated",
    inProgress: "In Progress",
    sellNow: "Sell Now",
    hold: "Hold",
    monitor: "Monitor",
    goodToSell: "Good to Sell",

    // Crops and Markets
    tomato: "Tomato",
    onion: "Onion",
    potato: "Potato",
    wheat: "Wheat",
    rice: "Rice",
    cotton: "Cotton",
    sugarcane: "Sugarcane",
    maize: "Maize",
    soybean: "Soybean",
    groundnut: "Groundnut",

    // Severity Levels
    low: "Low",
    medium: "Medium",
    high: "High",
    none: "None",

    // Time
    today: "Today",
    yesterday: "Yesterday",
    hoursAgo: "hours ago",
    daysAgo: "days ago",
    weeksAgo: "weeks ago",
  },
  hindi: {
    // Common
    welcome: "वापसी पर स्वागत है, राजेश!",
    farmStatus: "यहाँ है कि आज आपके खेत के साथ क्या हो रहा है।",
    loading: "लोड हो रहा है...",
    save: "सेव करें",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    search: "खोजें",
    filter: "फिल्टर",
    apply: "लागू करें",
    close: "बंद करें",

    // Navigation
    dashboard: "डैशबोर्ड",
    cropDiagnosis: "फसल निदान",
    marketAnalysis: "बाजार विश्लेषण",
    governmentSchemes: "सरकारी योजनाएं",
    expertConsultation: "विशेषज्ञ परामर्श",
    community: "समुदाय",
    agriNews: "कृषि समाचार",
    helpSupport: "सहायता और समर्थन",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    logout: "लॉग आउट",

    // Voice Assistant
    voiceAssistant: "आवाज सहायक",
    voiceDescription: "अपनी मातृभाषा में बोलें - मैं आपकी सभी कृषि आवश्यकताओं में मदद के लिए यहाँ हूँ",
    startSpeaking: "बोलना शुरू करें",
    listening: "सुन रहा हूँ...",
    stopAudio: "ऑडियो बंद करें",
    trySaying: "कहने की कोशिश करें:",

    // Quick Actions
    quickActions: "त्वरित कार्य",
    diagnoseCrop: "फसल निदान",
    checkPrices: "कीमतें जांचें",
    findSchemes: "योजनाएं खोजें",
    expertCall: "विशेषज्ञ कॉल",

    // Dashboard Stats
    farmSize: "खेत का आकार",
    cropsMonitored: "निगरानी की गई फसलें",
    marketAlerts: "बाजार अलर्ट",
    schemesApplied: "लागू योजनाएं",
    recentActivity: "हाल की गतिविधि",

    // Crop Diagnosis
    cropDiseaseTitle: "फसल रोग निदान",
    cropDiseaseDesc: "फसल रोगों का निदान करने और उपचार की सिफारिशें प्राप्त करने के लिए AI-संचालित छवि विश्लेषण का उपयोग करें।",
    uploadPhoto: "फोटो अपलोड करें",
    takePhoto: "फोटो लें",
    analyzingImage: "छवि का विश्लेषण...",
    diagnosisResults: "निदान परिणाम",
    immediateeTreatment: "तत्काल उपचार",
    localRemedies: "स्थानीय और किफायती उपचार",
    futurePrevention: "भविष्य की रोकथाम",
    recentDiagnoses: "हाल के निदान",
    photographyTips: "बेहतर निदान के लिए फोटोग्राफी टिप्स",
    goodLighting: "अच्छी रोशनी",
    closeupShots: "क्लोज-अप शॉट्स",
    multipleAngles: "कई कोण",
    cleanBackground: "साफ पृष्ठभूमि",

    // Market Analysis
    marketAnalysisTitle: "बाजार विश्लेषण",
    marketAnalysisDesc: "अधिकतम लाभ के लिए सूचित बिक्री निर्णय लेने हेतु वास्तविक समय बाजार मूल्य और रुझान प्राप्त करें।",
    selectCrop: "फसल चुनें",
    selectMarket: "बाजार चुनें",
    getLatestPrices: "नवीनतम कीमतें प्राप्त करें",
    fetchingPrices: "कीमतें प्राप्त कर रहे हैं...",
    recommendation: "सिफारिश:",
    marketSummary: "बाजार सारांश",
    weeklyTrends: "साप्ताहिक रुझान",
    marketTips: "बाजार टिप्स",
    bestSellingTimes: "सर्वोत्तम बिक्री समय",
    qualityMatters: "गुणवत्ता मायने रखती है",
    seasonalPatterns: "मौसमी पैटर्न",

    // Government Schemes
    governmentSchemesTitle: "सरकारी योजना नेवीगेटर",
    governmentSchemesDesc: "अपने कृषि कार्यों का समर्थन करने के लिए सरकारी कृषि योजनाओं और सब्सिडी की खोज करें और आवेदन करें।",
    yourAppliedSchemes: "आपकी आवेदित योजनाएं",
    trackStatus: "अपने योजना आवेदनों की स्थिति को ट्रैक करें",
    benefits: "लाभ",
    eligibility: "पात्रता",
    requiredDocuments: "आवश्यक दस्तावेज",
    deadline: "समय सीमा",
    applyNow: "अभी आवेदन करें",
    applicationTips: "आवेदन टिप्स",
    completeDocumentation: "पूर्ण दस्तावेजीकरण",
    meetDeadlines: "समय सीमा पूरी करें",
    verifyEligibility: "पात्रता सत्यापित करें",
    followUp: "फॉलो अप",

    // Expert Consultation
    expertConsultationTitle: "विशेषज्ञ परामर्श",
    expertConsultationDesc: "व्यक्तिगत सलाह और अपनी कृषि चुनौतियों के समाधान के लिए कृषि विशेषज्ञों से जुड़ें।",
    upcomingConsultations: "आगामी परामर्श",
    availableExperts: "उपलब्ध विशेषज्ञ",
    phoneConsultation: "फोन परामर्श",
    videoConsultation: "वीडियो परामर्श",
    chatSupport: "चैट सहायता",
    instantExpertAdvice: "तत्काल विशेषज्ञ सलाह",
    costEffectiveSolution: "लागत प्रभावी समाधान",
    available24x7: "24/7 उपलब्ध",
    visualCropAssessment: "दृश्य फसल मूल्यांकन",
    detailedExplanations: "विस्तृत स्पष्टीकरण",
    screenSharingSupport: "स्क्रीन साझाकरण सहायता",
    sharePhotosDocuments: "फोटो और दस्तावेज साझा करें",
    writtenRecommendations: "लिखित सिफारिशें",
    flexibleTiming: "लचीला समय",

    // Community
    farmerCommunity: "किसान समुदाय",
    communityDesc: "साथी किसानों से जुड़ें, अनुभव साझा करें, और समुदाय की सामूहिक बुद्धि से सीखें।",
    newDiscussion: "नई चर्चा",
    recentDiscussions: "हाल की चर्चाएं",
    categories: "श्रेणियां",
    topContributors: "शीर्ष योगदानकर्ता",
    communityStats: "समुदाय आंकड़े",
    totalMembers: "कुल सदस्य",
    activeDiscussions: "सक्रिय चर्चाएं",
    questionsAnswered: "उत्तरित प्रश्न",
    onlineNow: "अभी ऑनलाइन",

    // News
    agriculturalNews: "कृषि समाचार",
    newsDesc: "नवीनतम समाचार, मौसम चेतावनी, बाजार रुझान और कृषि विकास के साथ अपडेट रहें।",
    allNews: "सभी समाचार",
    weatherAlerts: "मौसम चेतावनी",
    marketUpdates: "बाजार अपडेट",
    governmentPolicy: "सरकारी नीति",
    technology: "प्रौद्योगिकी",
    research: "अनुसंधान",
    readMore: "और पढ़ें",
    weatherAlert: "मौसम चेतावनी",
    heavyRainfallWarning: "भारी बारिश की चेतावनी",
    stayUpdated: "अपडेट रहें",
    subscribeNewsletter: "न्यूजलेटर की सदस्यता लें",

    // Help & Support
    helpSupportTitle: "सहायता और समर्थन",
    helpDesc: "सामान्य प्रश्नों के उत्तर खोजें, संसाधनों तक पहुंचें, और Project Kisan का उपयोग करने के लिए सहायता प्राप्त करें।",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    contactSupport: "सहायता से संपर्क करें",
    getHelp: "सहायता प्राप्त करें",
    phoneSupport: "फोन सहायता",
    emailSupport: "ईमेल सहायता",
    liveChat: "लाइव चैट",
    helpResources: "सहायता संसाधन",
    gettingStartedGuide: "शुरुआती गाइड",
    videoTutorials: "वीडियो ट्यूटोरियल",
    featureDocumentation: "फीचर दस्तावेजीकरण",
    bestPractices: "सर्वोत्तम प्रथाएं",
    systemStatus: "सिस्टम स्थिति",
    operational: "परिचालन",
    maintenance: "रखरखाव",

    // Settings
    appearance: "दिखावट",
    theme: "थीम",
    chooseTheme: "अपनी पसंदीदा थीम चुनें",
    light: "हल्का",
    dark: "गहरा",
    system: "सिस्टम",
    languageRegion: "भाषा और क्षेत्र",
    language: "भाषा",
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    region: "क्षेत्र",
    setRegion: "अपना कृषि क्षेत्र सेट करें",
    weatherAlertsSettings: "मौसम चेतावनी",
    weatherAlertsDesc: "मौसम परिवर्तन के बारे में सूचित हों",
    marketPriceUpdates: "बाजार मूल्य अपडेट",
    marketPriceDesc: "बाजार मूल्य सूचनाएं प्राप्त करें",
    schemeAlerts: "सरकारी योजना चेतावनी",
    schemeAlertsDesc: "नई योजनाओं पर अपडेट रहें",
    diseaseWarnings: "फसल रोग चेतावनी",
    diseaseWarningsDesc: "अपने क्षेत्र में फसल रोगों के बारे में चेतावनी प्राप्त करें",
    voiceResponse: "आवाज प्रतिक्रिया",
    voiceResponseDesc: "आवाज प्रतिक्रिया सक्षम करें",
    voiceSpeed: "आवाज गति",
    voiceSpeedDesc: "आवाज प्रतिक्रिया गति समायोजित करें",
    slow: "धीमा",
    normal: "सामान्य",
    fast: "तेज",
    privacyData: "गोपनीयता और डेटा",
    dataCollection: "डेटा संग्रह",
    dataCollectionDesc: "बेहतर सिफारिशों के लिए डेटा संग्रह की अनुमति दें",
    locationServices: "स्थान सेवाएं",
    locationServicesDesc: "मौसम और बाजार डेटा के लिए स्थान का उपयोग करें",
    saveSettings: "सेटिंग्स सेव करें",

    // Profile
    farmSizeProfile: "खेत का आकार",
    experience: "अनुभव",
    primaryCrops: "मुख्य फसलें",
    contactInformation: "संपर्क जानकारी",
    about: "के बारे में",
    saveChanges: "परिवर्तन सेव करें",

    // Status and Actions
    active: "सक्रिय",
    applied: "आवेदित",
    completed: "पूर्ण",
    healthy: "स्वस्थ",
    treated: "उपचारित",
    inProgress: "प्रगति में",
    sellNow: "अभी बेचें",
    hold: "रोकें",
    monitor: "निगरानी करें",
    goodToSell: "बेचने के लिए अच्छा",

    // Crops and Markets
    tomato: "टमाटर",
    onion: "प्याज",
    potato: "आलू",
    wheat: "गेहूं",
    rice: "चावल",
    cotton: "कपास",
    sugarcane: "गन्ना",
    maize: "मक्का",
    soybean: "सोयाबीन",
    groundnut: "मूंगफली",

    // Severity Levels
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    none: "कोई नहीं",

    // Time
    today: "आज",
    yesterday: "कल",
    hoursAgo: "घंटे पहले",
    daysAgo: "दिन पहले",
    weeksAgo: "सप्ताह पहले",
  },
  punjabi: {
    // Common
    welcome: "ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ, ਰਾਜੇਸ਼!",
    farmStatus: "ਇਹ ਹੈ ਕਿ ਅੱਜ ਤੁਹਾਡੇ ਖੇਤ ਨਾਲ ਕੀ ਹੋ ਰਿਹਾ ਹੈ।",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    save: "ਸੇਵ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    edit: "ਸੰਪਾਦਿਤ ਕਰੋ",
    delete: "ਮਿਟਾਓ",
    search: "ਖੋਜੋ",
    filter: "ਫਿਲਟਰ",
    apply: "ਲਾਗੂ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",

    // Navigation
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    cropDiagnosis: "ਫਸਲ ਨਿਦਾਨ",
    marketAnalysis: "ਮਾਰਕੀਟ ਵਿਸ਼ਲੇਸ਼ਣ",
    governmentSchemes: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    expertConsultation: "ਮਾਹਰ ਸਲਾਹ",
    community: "ਕਮਿਊਨਿਟੀ",
    agriNews: "ਖੇਤੀ ਖ਼ਬਰਾਂ",
    helpSupport: "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    settings: "ਸੈਟਿੰਗਾਂ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    logout: "ਲਾਗ ਆਊਟ",

    // Voice Assistant
    voiceAssistant: "ਆਵਾਜ਼ ਸਹਾਇਕ",
    voiceDescription: "ਆਪਣੀ ਮਾਤ੍ਰਿਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ - ਮੈਂ ਤੁਹਾਡੀਆਂ ਸਾਰੀਆਂ ਖੇਤੀ ਲੋੜਾਂ ਵਿੱਚ ਮਦਦ ਲਈ ਇੱਥੇ ਹਾਂ",
    startSpeaking: "ਬੋਲਣਾ ਸ਼ੁਰੂ ਕਰੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
    stopAudio: "ਆਡੀਓ ਬੰਦ ਕਰੋ",
    trySaying: "ਕਹਿਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ:",

    // Quick Actions
    quickActions: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
    diagnoseCrop: "ਫਸਲ ਨਿਦਾਨ",
    checkPrices: "ਕੀਮਤਾਂ ਜਾਂਚੋ",
    findSchemes: "ਸਕੀਮਾਂ ਲੱਭੋ",
    expertCall: "ਮਾਹਰ ਕਾਲ",

    // Dashboard Stats
    farmSize: "ਖੇਤ ਦਾ ਆਕਾਰ",
    cropsMonitored: "ਨਿਗਰਾਨੀ ਕੀਤੀਆਂ ਫਸਲਾਂ",
    marketAlerts: "ਮਾਰਕੀਟ ਅਲਰਟ",
    schemesApplied: "ਲਾਗੂ ਸਕੀਮਾਂ",
    recentActivity: "ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ",

    // Crop Diagnosis
    cropDiseaseTitle: "ਫਸਲ ਰੋਗ ਨਿਦਾਨ",
    cropDiseaseDesc: "ਫਸਲ ਰੋਗਾਂ ਦਾ ਨਿਦਾਨ ਕਰਨ ਅਤੇ ਇਲਾਜ ਦੀਆਂ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ AI-ਸੰਚਾਲਿਤ ਚਿੱਤਰ ਵਿਸ਼ਲੇਸ਼ਣ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    uploadPhoto: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    takePhoto: "ਫੋਟੋ ਲਓ",
    analyzingImage: "ਚਿੱਤਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ...",
    diagnosisResults: "ਨਿਦਾਨ ਨਤੀਜੇ",
    immediateeTreatment: "ਤੁਰੰਤ ਇਲਾਜ",
    localRemedies: "ਸਥਾਨਕ ਅਤੇ ਕਿਫਾਇਤੀ ਉਪਚਾਰ",
    futurePrevention: "ਭਵਿੱਖ ਦੀ ਰੋਕਥਾਮ",
    recentDiagnoses: "ਹਾਲ ਦੇ ਨਿਦਾਨ",
    photographyTips: "ਬਿਹਤਰ ਨਿਦਾਨ ਲਈ ਫੋਟੋਗ੍ਰਾਫੀ ਟਿਪਸ",
    goodLighting: "ਚੰਗੀ ਰੋਸ਼ਨੀ",
    closeupShots: "ਕਲੋਜ਼-ਅਪ ਸ਼ਾਟਸ",
    multipleAngles: "ਕਈ ਕੋਣ",
    cleanBackground: "ਸਾਫ਼ ਪਿਛੋਕੜ",

    // Market Analysis
    marketAnalysisTitle: "ਮਾਰਕੀਟ ਵਿਸ਼ਲੇਸ਼ਣ",
    marketAnalysisDesc: "ਵੱਧ ਤੋਂ ਵੱਧ ਮੁਨਾਫੇ ਲਈ ਸੂਚਿਤ ਵਿਕਰੀ ਫੈਸਲੇ ਲੈਣ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਮਾਰਕੀਟ ਕੀਮਤਾਂ ਅਤੇ ਰੁਝਾਨ ਪ੍ਰਾਪਤ ਕਰੋ।",
    selectCrop: "ਫਸਲ ਚੁਣੋ",
    selectMarket: "ਮਾਰਕੀਟ ਚੁਣੋ",
    getLatestPrices: "ਨਵੀਨਤਮ ਕੀਮਤਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    fetchingPrices: "ਕੀਮਤਾਂ ਪ੍ਰਾਪਤ ਕਰ ਰਹੇ ਹਾਂ...",
    recommendation: "ਸਿਫਾਰਸ਼:",
    marketSummary: "ਮਾਰਕੀਟ ਸਾਰਾਂਸ਼",
    weeklyTrends: "ਹਫਤਾਵਾਰੀ ਰੁਝਾਨ",
    marketTips: "ਮਾਰਕੀਟ ਟਿਪਸ",
    bestSellingTimes: "ਸਭ ਤੋਂ ਵਧੀਆ ਵਿਕਰੀ ਸਮਾਂ",
    qualityMatters: "ਗੁਣਵੱਤਾ ਮਹੱਤਵਪੂਰਨ ਹੈ",
    seasonalPatterns: "ਮੌਸਮੀ ਪੈਟਰਨ",

    // Government Schemes
    governmentSchemesTitle: "ਸਰਕਾਰੀ ਸਕੀਮ ਨੇਵੀਗੇਟਰ",
    governmentSchemesDesc: "ਆਪਣੇ ਖੇਤੀ ਕਾਰਜਾਂ ਦਾ ਸਮਰਥਨ ਕਰਨ ਲਈ ਸਰਕਾਰੀ ਖੇਤੀ ਸਕੀਮਾਂ ਅਤੇ ਸਬਸਿਡੀ ਦੀ ਖੋਜ ਕਰੋ ਅਤੇ ਅਰਜ਼ੀ ਦਿਓ।",
    yourAppliedSchemes: "ਤੁਹਾਡੀਆਂ ਅਰਜ਼ੀ ਦਿੱਤੀਆਂ ਸਕੀਮਾਂ",
    trackStatus: "ਆਪਣੀਆਂ ਸਕੀਮ ਅਰਜ਼ੀਆਂ ਦੀ ਸਥਿਤੀ ਨੂੰ ਟਰੈਕ ਕਰੋ",
    benefits: "ਲਾਭ",
    eligibility: "ਯੋਗਤਾ",
    requiredDocuments: "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
    deadline: "ਸਮਾਂ ਸੀਮਾ",
    applyNow: "ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ",
    applicationTips: "ਅਰਜ਼ੀ ਟਿਪਸ",
    completeDocumentation: "ਪੂਰਾ ਦਸਤਾਵੇਜ਼ੀਕਰਨ",
    meetDeadlines: "ਸਮਾਂ ਸੀਮਾ ਪੂਰੀ ਕਰੋ",
    verifyEligibility: "ਯੋਗਤਾ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    followUp: "ਫਾਲੋ ਅਪ",

    // Expert Consultation
    expertConsultationTitle: "ਮਾਹਰ ਸਲਾਹ",
    expertConsultationDesc: "ਵਿਅਕਤੀਗਤ ਸਲਾਹ ਅਤੇ ਆਪਣੀਆਂ ਖੇਤੀ ਚੁਣੌਤੀਆਂ ਦੇ ਹੱਲ ਲਈ ਖੇਤੀ ਮਾਹਰਾਂ ਨਾਲ ਜੁੜੋ।",
    upcomingConsultations: "ਆਉਣ ਵਾਲੀਆਂ ਸਲਾਹਾਂ",
    availableExperts: "ਉਪਲਬਧ ਮਾਹਰ",
    phoneConsultation: "ਫੋਨ ਸਲਾਹ",
    videoConsultation: "ਵੀਡੀਓ ਸਲਾਹ",
    chatSupport: "ਚੈਟ ਸਹਾਇਤਾ",
    instantExpertAdvice: "ਤੁਰੰਤ ਮਾਹਰ ਸਲਾਹ",
    costEffectiveSolution: "ਲਾਗਤ ਪ੍ਰਭਾਵੀ ਹੱਲ",
    available24x7: "24/7 ਉਪਲਬਧ",
    visualCropAssessment: "ਦ੍ਰਿਸ਼ਟੀਗਤ ਫਸਲ ਮੁਲਾਂਕਣ",
    detailedExplanations: "ਵਿਸਤ੍ਰਿਤ ਸਪੱਸ਼ਟੀਕਰਨ",
    screenSharingSupport: "ਸਕ੍ਰੀਨ ਸਾਂਝਾਕਰਨ ਸਹਾਇਤਾ",
    sharePhotosDocuments: "ਫੋਟੋਆਂ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਸਾਂਝੇ ਕਰੋ",
    writtenRecommendations: "ਲਿਖਤੀ ਸਿਫਾਰਸ਼ਾਂ",
    flexibleTiming: "ਲਚਕਦਾਰ ਸਮਾਂ",

    // Community
    farmerCommunity: "ਕਿਸਾਨ ਕਮਿਊਨਿਟੀ",
    communityDesc: "ਸਾਥੀ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ, ਤਜਰਬੇ ਸਾਂਝੇ ਕਰੋ, ਅਤੇ ਕਮਿਊਨਿਟੀ ਦੀ ਸਮੂਹਿਕ ਬੁੱਧੀ ਤੋਂ ਸਿੱਖੋ।",
    newDiscussion: "ਨਵੀਂ ਚਰਚਾ",
    recentDiscussions: "ਹਾਲ ਦੀਆਂ ਚਰਚਾਵਾਂ",
    categories: "ਸ਼੍ਰੇਣੀਆਂ",
    topContributors: "ਸਿਖਰਲੇ ਯੋਗਦਾਨਕਰਤਾ",
    communityStats: "ਕਮਿਊਨਿਟੀ ਅੰਕੜੇ",
    totalMembers: "ਕੁੱਲ ਮੈਂਬਰ",
    activeDiscussions: "ਸਰਗਰਮ ਚਰਚਾਵਾਂ",
    questionsAnswered: "ਜਵਾਬ ਦਿੱਤੇ ਗਏ ਸਵਾਲ",
    onlineNow: "ਹੁਣ ਔਨਲਾਈਨ",

    // News
    agriculturalNews: "ਖੇਤੀ ਖ਼ਬਰਾਂ",
    newsDesc: "ਨਵੀਨਤਮ ਖ਼ਬਰਾਂ, ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ, ਮਾਰਕੀਟ ਰੁਝਾਨਾਂ ਅਤੇ ਖੇਤੀ ਵਿਕਾਸ ਨਾਲ ਅਪਡੇਟ ਰਹੋ।",
    allNews: "ਸਾਰੀਆਂ ਖ਼ਬਰਾਂ",
    weatherAlerts: "ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ",
    marketUpdates: "ਮਾਰਕੀਟ ਅਪਡੇਟਸ",
    governmentPolicy: "ਸਰਕਾਰੀ ਨੀਤੀ",
    technology: "ਤਕਨਾਲੋਜੀ",
    research: "ਖੋਜ",
    readMore: "ਹੋਰ ਪੜ੍ਹੋ",
    weatherAlert: "ਮੌਸਮ ਚੇਤਾਵਨੀ",
    heavyRainfallWarning: "ਭਾਰੀ ਬਾਰਿਸ਼ ਦੀ ਚੇਤਾਵਨੀ",
    stayUpdated: "ਅਪਡੇਟ ਰਹੋ",
    subscribeNewsletter: "ਨਿਊਜ਼ਲੈਟਰ ਦੀ ਸਦੱਸਤਾ ਲਓ",

    // Help & Support
    helpSupportTitle: "ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ",
    helpDesc: "ਆਮ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਲੱਭੋ, ਸਰੋਤਾਂ ਤੱਕ ਪਹੁੰਚ ਕਰੋ, ਅਤੇ Project Kisan ਦੀ ਵਰਤੋਂ ਕਰਨ ਲਈ ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਕਰੋ।",
    faq: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    contactSupport: "ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    getHelp: "ਮਦਦ ਪ੍ਰਾਪਤ ਕਰੋ",
    phoneSupport: "ਫੋਨ ਸਹਾਇਤਾ",
    emailSupport: "ਈਮੇਲ ਸਹਾਇਤਾ",
    liveChat: "ਲਾਈਵ ਚੈਟ",
    helpResources: "ਮਦਦ ਸਰੋਤ",
    gettingStartedGuide: "ਸ਼ੁਰੂਆਤੀ ਗਾਈਡ",
    videoTutorials: "ਵੀਡੀਓ ਟਿਊਟੋਰਿਅਲ",
    featureDocumentation: "ਫੀਚਰ ਦਸਤਾਵੇਜ਼ੀਕਰਨ",
    bestPractices: "ਸਭ ਤੋਂ ਵਧੀਆ ਅਭਿਆਸ",
    systemStatus: "ਸਿਸਟਮ ਸਥਿਤੀ",
    operational: "ਚਾਲੂ",
    maintenance: "ਰੱਖ-ਰਖਾਅ",

    // Settings
    appearance: "ਦਿੱਖ",
    theme: "ਥੀਮ",
    chooseTheme: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਥੀਮ ਚੁਣੋ",
    light: "ਹਲਕਾ",
    dark: "ਗੂੜ੍ਹਾ",
    system: "ਸਿਸਟਮ",
    languageRegion: "ਭਾਸ਼ਾ ਅਤੇ ਖੇਤਰ",
    language: "ਭਾਸ਼ਾ",
    chooseLanguage: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ",
    region: "ਖੇਤਰ",
    setRegion: "ਆਪਣਾ ਖੇਤੀ ਖੇਤਰ ਸੈੱਟ ਕਰੋ",
    weatherAlertsSettings: "ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ",
    weatherAlertsDesc: "ਮੌਸਮ ਤਬਦੀਲੀਆਂ ਬਾਰੇ ਸੂਚਿਤ ਹੋਵੋ",
    marketPriceUpdates: "ਮਾਰਕੀਟ ਕੀਮਤ ਅਪਡੇਟਸ",
    marketPriceDesc: "ਮਾਰਕੀਟ ਕੀਮਤ ਸੂਚਨਾਵਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    schemeAlerts: "ਸਰਕਾਰੀ ਸਕੀਮ ਚੇਤਾਵਨੀਆਂ",
    schemeAlertsDesc: "ਨਵੀਆਂ ਸਕੀਮਾਂ ਬਾਰੇ ਅਪਡੇਟ ਰਹੋ",
    diseaseWarnings: "ਫਸਲ ਰੋਗ ਚੇਤਾਵਨੀਆਂ",
    diseaseWarningsDesc: "ਆਪਣੇ ਖੇਤਰ ਵਿੱਚ ਫਸਲ ਰੋਗਾਂ ਬਾਰੇ ਚੇਤਾਵਨੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    voiceResponse: "ਆਵਾਜ਼ ਜਵਾਬ",
    voiceResponseDesc: "ਆਵਾਜ਼ ਜਵਾਬ ਸਮਰੱਥ ਕਰੋ",
    voiceSpeed: "ਆਵਾਜ਼ ਦੀ ਗਤੀ",
    voiceSpeedDesc: "ਆਵਾਜ਼ ਜਵਾਬ ਦੀ ਗਤੀ ਅਨੁਕੂਲਿਤ ਕਰੋ",
    slow: "ਹੌਲੀ",
    normal: "ਸਾਧਾਰਨ",
    fast: "ਤੇਜ਼",
    privacyData: "ਗੋਪਨੀਯਤਾ ਅਤੇ ਡੇਟਾ",
    dataCollection: "ਡੇਟਾ ਸੰਗ੍ਰਹਿ",
    dataCollectionDesc: "ਬਿਹਤਰ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਡੇਟਾ ਸੰਗ੍ਰਹਿ ਦੀ ਆਗਿਆ ਦਿਓ",
    locationServices: "ਸਥਾਨ ਸੇਵਾਵਾਂ",
    locationServicesDesc: "ਮੌਸਮ ਅਤੇ ਮਾਰਕੀਟ ਡੇਟਾ ਲਈ ਸਥਾਨ ਦੀ ਵਰਤੋਂ ਕਰੋ",
    saveSettings: "ਸੈਟਿੰਗਾਂ ਸੇਵ ਕਰੋ",

    // Profile
    farmSizeProfile: "ਖੇਤ ਦਾ ਆਕਾਰ",
    experience: "ਤਜਰਬਾ",
    primaryCrops: "ਮੁੱਖ ਫਸਲਾਂ",
    contactInformation: "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
    about: "ਬਾਰੇ",
    saveChanges: "ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ",

    // Status and Actions
    active: "ਸਰਗਰਮ",
    applied: "ਅਰਜ਼ੀ ਦਿੱਤੀ",
    completed: "ਪੂਰਾ",
    healthy: "ਸਿਹਤਮੰਦ",
    treated: "ਇਲਾਜ ਕੀਤਾ",
    inProgress: "ਪ੍ਰਗਤੀ ਵਿੱਚ",
    sellNow: "ਹੁਣ ਵੇਚੋ",
    hold: "ਰੋਕੋ",
    monitor: "ਨਿਗਰਾਨੀ ਕਰੋ",
    goodToSell: "ਵੇਚਣ ਲਈ ਚੰਗਾ",

    // Crops and Markets
    tomato: "ਟਮਾਟਰ",
    onion: "ਪਿਆਜ਼",
    potato: "ਆਲੂ",
    wheat: "ਕਣਕ",
    rice: "ਚਾਵਲ",
    cotton: "ਕਪਾਹ",
    sugarcane: "ਗੰਨਾ",
    maize: "ਮੱਕੀ",
    soybean: "ਸੋਇਆਬੀਨ",
    groundnut: "ਮੂੰਗਫਲੀ",

    // Severity Levels
    low: "ਘੱਟ",
    medium: "ਮੱਧਮ",
    high: "ਉੱਚ",
    none: "ਕੋਈ ਨਹੀਂ",

    // Time
    today: "ਅੱਜ",
    yesterday: "ਕੱਲ੍ਹ",
    hoursAgo: "ਘੰਟੇ ਪਹਿਲਾਂ",
    daysAgo: "ਦਿਨ ਪਹਿਲਾਂ",
    weeksAgo: "ਹਫ਼ਤੇ ਪਹਿਲਾਂ",
  },
  gujarati: {
    // Common
    welcome: "પાછા આવવા બદલ સ્વાગત છે, રાજેશ!",
    farmStatus: "આજે તમારા ખેતર સાથે શું થઈ રહ્યું છે તે અહીં છે।",
    loading: "લોડ થઈ રહ્યું છે...",
    save: "સેવ કરો",
    cancel: "રદ કરો",
    edit: "સંપાદિત કરો",
    delete: "કાઢી નાખો",
    search: "શોધો",
    filter: "ફિલ્ટર",
    apply: "લાગુ કરો",
    close: "બંધ કરો",

    // Navigation
    dashboard: "ડેશબોર્ડ",
    cropDiagnosis: "પાક નિદાન",
    marketAnalysis: "બજાર વિશ્લેષણ",
    governmentSchemes: "સરકારી યોજનાઓ",
    expertConsultation: "નિષ્ણાત સલાહ",
    community: "સમુદાય",
    agriNews: "કૃષિ સમાચાર",
    helpSupport: "મદદ અને સહાય",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    notifications: "સૂચનાઓ",
    logout: "લોગ આઉટ",

    // Voice Assistant
    voiceAssistant: "અવાજ સહાયક",
    voiceDescription: "તમારી માતૃભાષામાં બોલો - હું તમારી બધી ખેતીની જરૂરિયાતોમાં મદદ કરવા અહીં છું",
    startSpeaking: "બોલવાનું શરૂ કરો",
    listening: "સાંભળી રહ્યો છું...",
    stopAudio: "ઓડિયો બંધ કરો",
    trySaying: "ક્હેવાનો પ્રયાસ કરો:",

    // Quick Actions
    quickActions: "ઝડપી ક્રિયાઓ",
    diagnoseCrop: "પાક નિદાન",
    checkPrices: "કિંમતો તપાસો",
    findSchemes: "યોજનાઓ શોધો",
    expertCall: "નિષ્ણાત કૉલ",

    // Dashboard Stats
    farmSize: "ખેત���નું કદ",
    cropsMonitored: "નિરીક્ષણ કરેલ પાકો",
    marketAlerts: "બજાર ચેતવણીઓ",
    schemesApplied: "લાગુ યોજનાઓ",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",

    // Crop Diagnosis
    cropDiseaseTitle: "પાક રોગ નિદાન",
    cropDiseaseDesc: "પાક રોગોનું નિદાન કરવા અને સારવારની ભલામણો મેળવવા માટે AI-સંચાલિત છબી વિશ્લેષણનો ઉપયોગ કરો।",
    uploadPhoto: "ફોટો અપલોડ કરો",
    takePhoto: "ફોટો લો",
    analyzingImage: "છબીનું વિશ્લેષણ...",
    diagnosisResults: "નિદાન પરિણામો",
    immediateeTreatment: "તાત્કાલિક સારવાર",
    localRemedies: "સ્થાનિક અને પોસાય તેવા ઉપચાર",
    futurePrevention: "ભવિષ્યની રોકથામ",
    recentDiagnoses: "તાજેતરના નિદાન",
    photographyTips: "વધુ સારા નિદાન માટે ફોટોગ્રાફી ટિપ્સ",
    goodLighting: "સારી લાઇટિંગ",
    closeupShots: "ક્લોઝ-અપ શોટ્સ",
    multipleAngles: "બહુવિધ કોણ",
    cleanBackground: "સ્વચ્છ પૃષ્ઠભૂમિ",

    // Market Analysis
    marketAnalysisTitle: "બજાર વિશ્લેષણ",
    marketAnalysisDesc: "મહત્તમ નફા માટે માહિતીગાર વેચાણ નિર્ણયો લેવા માટે રીઅલ-ટાઇમ બજાર કિંમતો અને વલણો મેળવો।",
    selectCrop: "પાક પસંદ કરો",
    selectMarket: "બજાર પસંદ કરો",
    getLatestPrices: "નવીનતમ કિંમતો મેળવો",
    fetchingPrices: "કિંમતો મેળવી રહ્યા છીએ...",
    recommendation: "ભલામણ:",
    marketSummary: "બજાર સારાંશ",
    weeklyTrends: "સાપ્તાહિક વલણો",
    marketTips: "બજાર ટિપ્સ",
    bestSellingTimes: "શ્રેષ્ઠ વેચાણ સમય",
    qualityMatters: "ગુણવત્તા મહત્વની છે",
    seasonalPatterns: "મોસમી પેટર્ન",

    // Government Schemes
    governmentSchemesTitle: "સરકારી યોજના નેવિગેટર",
    governmentSchemesDesc: "તમારા ખેતી કામગીરીને ટેકો આપવા માટે સરકારી કૃષિ યોજનાઓ અને સબસિડીની શોધ કરો અને અરજી કરો।",
    yourAppliedSchemes: "તમારી અરજી કરેલ યોજનાઓ",
    trackStatus: "તમારી યોજના અરજીઓની સ્થિતિને ટ્રેક કરો",
    benefits: "લાભો",
    eligibility: "પાત્રતા",
    requiredDocuments: "જરૂરી દસ્તાવેજો",
    deadline: "સમય મર્યાદા",
    applyNow: "હવે અરજી કરો",
    applicationTips: "અરજી ટિપ્સ",
    completeDocumentation: "સંપૂર્ણ દસ્તાવેજીકરણ",
    meetDeadlines: "સમય મર્યાદા પૂરી કરો",
    verifyEligibility: "પાત્રતા ચકાસો",
    followUp: "ફોલો અપ",

    // Expert Consultation
    expertConsultationTitle: "નિષ્ણાત સલાહ",
    expertConsultationDesc: "વ્યક્તિગત સલાહ અને તમારી ખેતીની પડકારોના ઉકેલો માટે કૃષિ નિષ્ણાતો સાથે જોડાઓ।",
    upcomingConsultations: "આગામી સલાહ",
    availableExperts: "ઉપલબ્ધ નિષ્ણાતો",
    phoneConsultation: "ફોન સલાહ",
    videoConsultation: "વિડિયો સલાહ",
    chatSupport: "ચેટ સહાય",
    instantExpertAdvice: "તાત્કાલિક નિષ્ણાત સલાહ",
    costEffectiveSolution: "ખર્ચ અસરકારક ઉકેલ",
    available24x7: "24/7 ઉપલબ્ધ",
    visualCropAssessment: "દ્રશ્ય પાક મૂલ્યાંકન",
    detailedExplanations: "વિગતવાર સમજૂતીઓ",
    screenSharingSupport: "સ્ક્રીન શેરિંગ સહાય",
    sharePhotosDocuments: "ફોટા અને દસ્તાવેજો શેર કરો",
    writtenRecommendations: "લેખિત ભલામણો",
    flexibleTiming: "લવચીક સમય",

    // Community
    farmerCommunity: "ખેડૂત સમુદાય",
    communityDesc: "સાથી ખેડૂતો સાથે જોડાઓ, અનુભવો શેર કરો, અને સમુદાયની સામૂહિક બુદ્ધિમત્તામાંથી શીખો।",
    newDiscussion: "નવી ચર્ચા",
    recentDiscussions: "તાજેતરની ચર્ચાઓ",
    categories: "શ્રેણીઓ",
    topContributors: "ટોચના યોગદાનકર્તાઓ",
    communityStats: "સમુદાય આંકડા",
    totalMembers: "કુલ સભ્યો",
    activeDiscussions: "સક્રિય ચર્ચાઓ",
    questionsAnswered: "જવાબ આપેલા પ્રશ્નો",
    onlineNow: "હવે ઓનલાઇન",

    // News
    agriculturalNews: "કૃષિ સમાચાર",
    newsDesc: "નવીનતમ સમાચાર, હવામાન ચેતવણીઓ, બજાર વલણો અને કૃષિ વિકાસ સાથે અપડેટ રહો।",
    allNews: "બધા સમાચાર",
    weatherAlerts: "હવામાન ચેતવણીઓ",
    marketUpdates: "બજાર અપડેટ્સ",
    governmentPolicy: "સરકારી નીતિ",
    technology: "ટેકનોલોજી",
    research: "સંશોધન",
    readMore: "વધુ વાંચો",
    weatherAlert: "હવામાન ચેતવણી",
    heavyRainfallWarning: "ભારે વરસાદની ચેતવણી",
    stayUpdated: "અપડેટ રહો",
    subscribeNewsletter: "ન્યૂઝલેટરની સબ્સ્ક્રિપ્શન લો",

    // Help & Support
    helpSupportTitle: "મદદ અને સહાય",
    helpDesc: "સામાન્ય પ્રશ્નોના જવાબો શોધો, સંસાધનોને ઍક્સેસ કરો, અને Project Kisan નો ઉપયોગ કરવા માટે સહાય મેળવો।",
    faq: "વારંવાર પૂછાતા પ્રશ્નો",
    contactSupport: "સહાયનો સંપર્ક કરો",
    getHelp: "મદદ મેળવો",
    phoneSupport: "ફોન સહાય",
    emailSupport: "ઇમેઇલ સહાય",
    liveChat: "લાઇવ ચેટ",
    helpResources: "મદદ સંસાધનો",
    gettingStartedGuide: "શરૂઆતી માર્ગદર્શિકા",
    videoTutorials: "વિડિયો ટ્યુટોરિયલ્સ",
    featureDocumentation: "ફીચર દસ્તાવેજીકરણ",
    bestPractices: "શ્રેષ્ઠ પ્રથાઓ",
    systemStatus: "સિસ્ટમ સ્થિતિ",
    operational: "કાર્યરત",
    maintenance: "જાળવણી",

    // Settings
    appearance: "દેખાવ",
    theme: "થીમ",
    chooseTheme: "તમારી પસંદગીની થીમ પસંદ કરો",
    light: "હળવી",
    dark: "ઘેરી",
    system: "સિસ્ટમ",
    languageRegion: "ભાષા અને પ્રદેશ",
    language: "ભાષા",
    chooseLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    region: "પ્રદેશ",
    setRegion: "તમારો ખેતી પ્રદેશ સેટ કરો",
    weatherAlertsSettings: "હવામાન ચેતવણીઓ",
    weatherAlertsDesc: "હવામાન ફેરફારો વિશે સૂચિત થાઓ",
    marketPriceUpdates: "બજાર કિંમત અપડેટ્સ",
    marketPriceDesc: "બજાર કિંમત સૂચનાઓ મેળવો",
    schemeAlerts: "સરકારી યોજના ચેતવણીઓ",
    schemeAlertsDesc: "નવી યોજનાઓ પર અપડેટ રહો",
    diseaseWarnings: "પાક રોગ ચેતવણીઓ",
    diseaseWarningsDesc: "તમારા વિસ્તારમાં પાક રોગો વિશે ચેતવણીઓ મેળવો",
    voiceResponse: "અવાજ પ્રતિસાદ",
    voiceResponseDesc: "અવાજ પ્રતિસાદ સક્ષમ કરો",
    voiceSpeed: "અવાજની ગતિ",
    voiceSpeedDesc: "અવાજ પ્રતિસાદની ગતિ સમાયોજિત કરો",
    slow: "ધીમી",
    normal: "સામાન્ય",
    fast: "ઝડપી",
    privacyData: "ગોપનીયતા અને ડેટા",
    dataCollection: "ડેટા સંગ્રહ",
    dataCollectionDesc: "વધુ સારી ભલામણો માટે ડેટા સંગ્રહની મંજૂરી આપો",
    locationServices: "સ્થાન સેવાઓ",
    locationServicesDesc: "હવામાન અને બજાર ડેટા માટે સ્થાનનો ઉપયોગ કરો",
    saveSettings: "સેટિંગ્સ સેવ કરો",

    // Profile
    farmSizeProfile: "ખેતરનું કદ",
    experience: "અનુભવ",
    primaryCrops: "મુખ્ય પાકો",
    contactInformation: "સંપર્ક માહિતી",
    about: "વિશે",
    saveChanges: "ફેરફારો સેવ કરો",

    // Status and Actions
    active: "સક્રિય",
    applied: "અરજી કરેલ",
    completed: "પૂર્ણ",
    healthy: "સ્વસ્થ",
    treated: "સારવાર કરેલ",
    inProgress: "પ્રગતિમાં",
    sellNow: "હવે વેચો",
    hold: "રોકો",
    monitor: "નિરીક્ષણ કરો",
    goodToSell: "વેચવા માટે સારું",

    // Crops and Markets
    tomato: "ટમેટા",
    onion: "ડુંગળી",
    potato: "બટાકા",
    wheat: "ઘઉં",
    rice: "ચોખા",
    cotton: "કપાસ",
    sugarcane: "શેરડી",
    maize: "મકાઈ",
    soybean: "સોયાબીન",
    groundnut: "મગફળી",

    // Severity Levels
    low: "ઓછું",
    medium: "મધ્યમ",
    high: "ઊંચું",
    none: "કંઈ નહીં",

    // Time
    today: "આજે",
    yesterday: "ગઈકાલે",
    hoursAgo: "કલાકો પહેલાં",
    daysAgo: "દિવસો પહેલાં",
    weeksAgo: "અઠવાડિયા પહેલાં",
  },
  marathi: {
    // Common
    welcome: "परत आल्याबद्दल स्वागत आहे, राजेश!",
    farmStatus: "आज तुमच्या शेतात काय घडत आहे ते येथे आहे।",
    loading: "लोड होत आहे...",
    save: "सेव्ह करा",
    cancel: "रद्द करा",
    edit: "संपादित करा",
    delete: "हटवा",
    search: "शोधा",
    filter: "फिल्टर",
    apply: "लागू करा",
    close: "बंद करा",

    // Navigation
    dashboard: "डॅशबोर्ड",
    cropDiagnosis: "पीक निदान",
    marketAnalysis: "बाजार विश्लेषण",
    governmentSchemes: "सरकारी योजना",
    expertConsultation: "तज्ञ सल्ला",
    community: "समुदाय",
    agriNews: "कृषी बातम्या",
    helpSupport: "मदत आणि सहाय्य",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    notifications: "सूचना",
    logout: "लॉग आउट",

    // Voice Assistant
    voiceAssistant: "आवाज सहाय्यक",
    voiceDescription: "तुमच्या मातृभाषेत बोला - मी तुमच्या सर्व शेतीच्या गरजांमध्ये मदत करण्यासाठी येथे आहे",
    startSpeaking: "बोलणे सुरू करा",
    listening: "ऐकत आहे...",
    stopAudio: "ऑडिओ बंद करा",
    trySaying: "म्हणण्याचा प्रयत्न करा:",

    // Quick Actions
    quickActions: "त्वरित क्रिया",
    diagnoseCrop: "पीक निदान",
    checkPrices: "किंमती तपासा",
    findSchemes: "योजना शोधा",
    expertCall: "तज्ञ कॉल",

    // Dashboard Stats
    farmSize: "शेताचा आकार",
    cropsMonitored: "निरीक्षण केलेली पिके",
    marketAlerts: "बाजार सूचना",
    schemesApplied: "लागू योजना",
    recentActivity: "अलीकडील क्रियाकलाप",

    // Crop Diagnosis
    cropDiseaseTitle: "पीक रोग निदान",
    cropDiseaseDesc: "पीक रोगांचे निदान करण्यासाठी आणि उपचार शिफारसी मिळवण्यासाठी AI-चालित प्रतिमा विश्लेषण वापरा।",
    uploadPhoto: "फोटो अपलोड करा",
    takePhoto: "फोटो घ्या",
    analyzingImage: "प्रतिमेचे विश्लेषण...",
    diagnosisResults: "निदान परिणाम",
    immediateeTreatment: "तत्काळ उपचार",
    localRemedies: "स्थानिक आणि परवडणारे उपचार",
    futurePrevention: "भविष्यातील प्रतिबंध",
    recentDiagnoses: "अलीकडील निदान",
    photographyTips: "चांगल्या निदानासाठी फोटोग्राफी टिप्स",
    goodLighting: "चांगली प्रकाशयोजना",
    closeupShots: "क्लोज-अप शॉट्स",
    multipleAngles: "अनेक कोन",
    cleanBackground: "स्वच्छ पार्श्वभूमी",

    // Market Analysis
    marketAnalysisTitle: "बाजार विश्लेषण",
    marketAnalysisDesc: "जास्तीत जास्त नफ्यासाठी माहितीपूर्ण विक्री निर्णय घेण्यासाठी रिअल-टाइम बाजार किंमती आणि ट्रेंड मिळवा।",
    selectCrop: "पीक निवडा",
    selectMarket: "बाजार निवडा",
    getLatestPrices: "नवीनतम किंमती मिळवा",
    fetchingPrices: "किंमती मिळवत आहे...",
    recommendation: "शिफारस:",
    marketSummary: "बाजार सारांश",
    weeklyTrends: "साप्ताहिक ट्रेंड",
    marketTips: "बाजार टिप्स",
    bestSellingTimes: "सर्वोत्तम विक्री वेळा",
    qualityMatters: "गुणवत्ता महत्त्वाची आहे",
    seasonalPatterns: "हंगामी पॅटर्न",

    // Government Schemes
    governmentSchemesTitle: "सरकारी योजना नेव्हिगेटर",
    governmentSchemesDesc: "तुमच्या शेती कामकाजाला पाठिंबा देण्यासाठी सरकारी कृषी योजना आणि अनुदान शोधा आणि अर्ज करा।",
    yourAppliedSchemes: "तुमच्या अर्ज केलेल्या योजना",
    trackStatus: "तुमच्या योजना अर्जांची स्थिती ट्रॅक करा",
    benefits: "फायदे",
    eligibility: "पात्रता",
    requiredDocuments: "आवश्यक कागदपत्रे",
    deadline: "अंतिम मुदत",
    applyNow: "आता अर्ज करा",
    applicationTips: "अर्ज टिप्स",
    completeDocumentation: "संपूर्ण कागदपत्रे",
    meetDeadlines: "अंतिम मुदत पूर्ण करा",
    verifyEligibility: "पात्रता तपासा",
    followUp: "फॉलो अप",

    // Expert Consultation
    expertConsultationTitle: "तज्ञ सल्ला",
    expertConsultationDesc: "वैयक्तिक सल्ला आणि तुमच्या शेतीच्या आव्हानांचे उपाय मिळवण्यासाठी कृषी तज्ञांशी जोडा।",
    upcomingConsultations: "आगामी सल्लामसलत",
    availableExperts: "उपलब्ध तज्ञ",
    phoneConsultation: "फोन सल्ला",
    videoConsultation: "व्हिडिओ सल्ला",
    chatSupport: "चॅट सहाय्य",
    instantExpertAdvice: "तत्काळ तज्ञ सल्ला",
    costEffectiveSolution: "किफायतशीर उपाय",
    available24x7: "24/7 उपलब्ध",
    visualCropAssessment: "दृश्य पीक मूल्यांकन",
    detailedExplanations: "तपशीलवार स्पष्टीकरण",
    screenSharingSupport: "स्क्रीन शेअरिंग सहाय्य",
    sharePhotosDocuments: "फोटो आणि कागदपत्रे शेअर करा",
    writtenRecommendations: "लेखी शिफारसी",
    flexibleTiming: "लवचिक वेळ",

    // Community
    farmerCommunity: "शेतकरी समुदाय",
    communityDesc: "सहकारी शेतकऱ्यांशी जोडा, अनुभव शेअर करा, आणि समुदायाच्या सामूहिक बुद्धिमत्तेतून शिका।",
    newDiscussion: "नवीन चर्चा",
    recentDiscussions: "अलीकडील चर्चा",
    categories: "श्रेणी",
    topContributors: "शीर्ष योगदानकर्ते",
    communityStats: "समुदाय आकडेवारी",
    totalMembers: "एकूण सदस्य",
    activeDiscussions: "सक्रिय चर्चा",
    questionsAnswered: "उत्तर दिलेले प्रश्न",
    onlineNow: "आता ऑनलाइन",

    // News
    agriculturalNews: "कृषी बातम्या",
    newsDesc: "नवीनतम बातम्या, हवामान चेतावणी, बाजार ट्रेंड आणि कृषी विकासासह अपडेट राहा।",
    allNews: "सर्व बातम्या",
    weatherAlerts: "हवामान चेतावणी",
    marketUpdates: "बाजार अपडेट्स",
    governmentPolicy: "सरकारी धोरण",
    technology: "तंत्रज्ञान",
    research: "संशोधन",
    readMore: "अधिक वाचा",
    weatherAlert: "हवामान चेतावणी",
    heavyRainfallWarning: "मुसळधार पावसाची चेतावणी",
    stayUpdated: "अपडेट राहा",
    subscribeNewsletter: "न्यूजलेटरची सबस्क्रिप्शन घ्या",

    // Help & Support
    helpSupportTitle: "मदत आणि सहाय्य",
    helpDesc: "सामान्य प्रश्नांची उत्तरे शोधा, संसाधनांमध्ये प्रवेश करा, आणि Project Kisan वापरण्यासाठी सहाय्य मिळवा।",
    faq: "वारंवार विचारले जाणारे प्रश्न",
    contactSupport: "सहाय्याशी संपर्क साधा",
    getHelp: "मदत मिळवा",
    phoneSupport: "फोन सहाय्य",
    emailSupport: "ईमेल सहाय्य",
    liveChat: "लाइव्ह चॅट",
    helpResources: "मदत संसाधने",
    gettingStartedGuide: "सुरुवातीचे मार्गदर्शन",
    videoTutorials: "व्हिडिओ ट्यूटोरियल",
    featureDocumentation: "वैशिष्ट्य दस्तऐवजीकरण",
    bestPractices: "सर्वोत्तम पद्धती",
    systemStatus: "सिस्टम स्थिती",
    operational: "कार्यरत",
    maintenance: "देखभाल",

    // Settings
    appearance: "दिसणे",
    theme: "थीम",
    chooseTheme: "तुमची पसंतीची थीम निवडा",
    light: "हलकी",
    dark: "गडद",
    system: "सिस्टम",
    languageRegion: "भाषा आणि प्रदेश",
    language: "भाषा",
    chooseLanguage: "तुमची पसंतीची भाषा निवडा",
    region: "प्रदेश",
    setRegion: "तुमचा शेती प्रदेश सेट करा",
    weatherAlertsSettings: "हवामान चेतावणी",
    weatherAlertsDesc: "हवामान बदलांबद्दल सूचित व्हा",
    marketPriceUpdates: "बाजार किंमत अपडेट्स",
    marketPriceDesc: "बाजार किंमत सूचना मिळवा",
    schemeAlerts: "सरकारी योजना चेतावणी",
    schemeAlertsDesc: "नवीन योजनांवर अपडेट राहा",
    diseaseWarnings: "पीक रोग चेतावणी",
    diseaseWarningsDesc: "तुमच्या क्षेत्रातील पीक रोगांबद्दल चेतावणी मिळवा",
    voiceResponse: "आवाज प्रतिसाद",
    voiceResponseDesc: "आवाज प्रतिसाद सक्षम करा",
    voiceSpeed: "आवाजाचा वेग",
    voiceSpeedDesc: "आवाज प्रतिसादाचा वेग समायोजित करा",
    slow: "मंद",
    normal: "सामान्य",
    fast: "वेगवान",
    privacyData: "गोपनीयता आणि डेटा",
    dataCollection: "डेटा संकलन",
    dataCollectionDesc: "चांगल्या शिफारसींसाठी डेटा संकलनास परवानगी द्या",
    locationServices: "स्थान सेवा",
    locationServicesDesc: "हवामान आणि बाजार डेटासाठी स्थान वापरा",
    saveSettings: "सेटिंग्ज सेव्ह करा",

    // Profile
    farmSizeProfile: "शेताचा आकार",
    experience: "अनुभव",
    primaryCrops: "मुख्य पिके",
    contactInformation: "संपर्क माहिती",
    about: "बद्दल",
    saveChanges: "बदल सेव्ह करा",

    // Status and Actions
    active: "सक्रिय",
    applied: "अर्ज केला",
    completed: "पूर्ण",
    healthy: "निरोगी",
    treated: "उपचार केले",
    inProgress: "प्रगतीत",
    sellNow: "आता विका",
    hold: "थांबवा",
    monitor: "निरीक्षण करा",
    goodToSell: "विकण्यासाठी चांगले",

    // Crops and Markets
    tomato: "टोमॅटो",
    onion: "कांदा",
    potato: "बटाटा",
    wheat: "गहू",
    rice: "तांदूळ",
    cotton: "कापूस",
    sugarcane: "ऊस",
    maize: "मका",
    soybean: "सोयाबीन",
    groundnut: "भुईमूग",

    // Severity Levels
    low: "कमी",
    medium: "मध्यम",
    high: "उच्च",
    none: "काहीही नाही",

    // Time
    today: "आज",
    yesterday: "काल",
    hoursAgo: "तासांपूर्वी",
    daysAgo: "दिवसांपूर्वी",
    weeksAgo: "आठवड्यांपूर्वी",
  },
  telugu: {
    // Common
    welcome: "తిరిగి వచ్చినందుకు స్వాగతం, రాజేష్!",
    farmStatus: "ఈరోజు మీ వ్యవసాయంతో ఏమి జరుగుతుందో ఇక్కడ ఉంది।",
    loading: "లోడ్ అవుతోంది...",
    save: "సేవ్ చేయండి",
    cancel: "రద్దు చేయండి",
    edit: "సవరించండి",
    delete: "తొలగించండి",
    search: "వెతకండి",
    filter: "ఫిల్టర్",
    apply: "వర్తింపజేయండి",
    close: "మూసివేయండి",

    // Navigation
    dashboard: "డ్యాష్‌బోర్డ్",
    cropDiagnosis: "పంట నిర్ధారణ",
    marketAnalysis: "మార్కెట్ విశ్లేషణ",
    governmentSchemes: "ప్రభుత్వ పథకాలు",
    expertConsultation: "నిపుణుల సలహా",
    community: "కమ్యూనిటీ",
    agriNews: "వ్యవసాయ వార్తలు",
    helpSupport: "సహాయం మరియు మద్దతు",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్‌లు",
    notifications: "నోటిఫికేషన్‌లు",
    logout: "లాగ్ అవుట్",

    // Voice Assistant
    voiceAssistant: "వాయిస్ అసిస్టెంట్",
    voiceDescription: "మీ మాతృభాషలో మాట్లాడండి - మీ అన్ని వ్యవసాయ అవసరాలలో సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను",
    startSpeaking: "మాట్లాడటం ప్రారంభించండి",
    listening: "వింటున్నాను...",
    stopAudio: "ఆడియో ఆపండి",
    trySaying: "చెప్పడానికి ప్రయత్నించండి:",

    // Quick Actions
    quickActions: "త్వరిత చర్యలు",
    diagnoseCrop: "పంట నిర్ధారణ",
    checkPrices: "ధరలు తనిఖీ చేయండి",
    findSchemes: "పథకాలు కనుగొనండి",
    expertCall: "నిపుణుల కాల్",

    // Dashboard Stats
    farmSize: "వ్యవసాయ పరిమాణం",
    cropsMonitored: "పర్యవేక్షించిన పంటలు",
    marketAlerts: "మార్కెట్ హెచ్చరికలు",
    schemesApplied: "వర్తించిన పథకాలు",
    recentActivity: "ఇటీవలి కార్యకలాపాలు",

    // Crop Diagnosis
    cropDiseaseTitle: "పంట వ్యాధి నిర్ధారణ",
    cropDiseaseDesc: "పంట వ్యాధుల నిర్ధారణ మరియు చికిత్స సిఫార్సులను పొందడానికి AI-శక్తితో కూడిన చిత్ర విశ్లేషణను ఉపయోగించండి।",
    uploadPhoto: "ఫోటో అప్‌లోడ్ చేయండి",
    takePhoto: "ఫోటో తీయండి",
    analyzingImage: "చిత్రం విశ్లేషిస్తోంది...",
    diagnosisResults: "నిర్ధారణ ఫలితాలు",
    immediateeTreatment: "తక్షణ చికిత్స",
    localRemedies: "స్థానిక మరియు సరసమైన చికిత్సలు",
    futurePrevention: "భవిష్యత్ నివారణ",
    recentDiagnoses: "ఇటీవలి నిర్ధారణలు",
    photographyTips: "మెరుగైన నిర్ధారణ కోసం ఫోటోగ్రఫీ చిట్కాలు",
    goodLighting: "మంచి వెలుతురు",
    closeupShots: "క్లోజ్-అప్ షాట్‌లు",
    multipleAngles: "అనేక కోణాలు",
    cleanBackground: "శుభ్రమైన నేపథ్యం",

    // Market Analysis
    marketAnalysisTitle: "మార్కెట్ విశ్లేషణ",
    marketAnalysisDesc: "గరిష్ట లాభాల కోసం సమాచార విక్రయ నిర్ణయాలు తీసుకోవడానికి రియల్-టైమ్ మార్కెట్ ధరలు మరియు ట్రెండ్‌లను పొందండి।",
    selectCrop: "పంట ఎంచుకోండి",
    selectMarket: "మార్కెట్ ఎంచుకోండి",
    getLatestPrices: "తాజా ధరలను పొందండి",
    fetchingPrices: "ధరలను పొందుతోంది...",
    recommendation: "సిఫార్సు:",
    marketSummary: "మార్కెట్ సారాంశం",
    weeklyTrends: "వారపు ట్రెండ్‌లు",
    marketTips: "మార్కెట్ చిట్కాలు",
    bestSellingTimes: "ఉత్తమ విక్రయ సమయాలు",
    qualityMatters: "నాణ్యత ముఖ్యం",
    seasonalPatterns: "కాలానుగుణ నమూనాలు",

    // Government Schemes
    governmentSchemesTitle: "ప్రభుత్వ పథకాల నావిగేటర్",
    governmentSchemesDesc: "మీ వ్యవసాయ కార్యకలాపాలకు మద్దతు ఇవ్వడానికి ప్రభుత్వ వ్యవసాయ పథకాలు మరియు సబ్సిడీలను కనుగొనండి మరియు దరఖాస్తు చేయండి।",
    yourAppliedSchemes: "మీ దరఖాస్తు చేసిన పథకాలు",
    trackStatus: "మీ పథక దరఖాస్తుల స్థితిని ట్రాక్ చేయండి",
    benefits: "ప్రయోజనాలు",
    eligibility: "అర్హత",
    requiredDocuments: "అవసరమైన పత్రాలు",
    deadline: "గడువు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    applicationTips: "దరఖాస్తు చిట్కాలు",
    completeDocumentation: "పూర్తి డాక్యుమెంటేషన్",
    meetDeadlines: "గడువులను పూర్తి చేయండి",
    verifyEligibility: "అర్హతను ధృవీకరించండి",
    followUp: "ఫాలో అప్",

    // Expert Consultation
    expertConsultationTitle: "నిపుణుల సలహా",
    expertConsultationDesc: "వ్యక్తిగత సలహా మరియు మీ వ్యవసాయ సవాళ్లకు పరిష్కారాల కోసం వ్యవసాయ నిపుణులతో కనెక్ట్ అవ్వండి।",
    upcomingConsultations: "రాబోయే సలహాలు",
    availableExperts: "అందుబాటులో ఉన్న నిపుణులు",
    phoneConsultation: "ఫోన్ సలహా",
    videoConsultation: "వీడియో సలహా",
    chatSupport: "చాట్ మద్దతు",
    instantExpertAdvice: "తక్షణ నిపుణుల సలహా",
    costEffectiveSolution: "ఖర్చు ప్రభావవంతమైన పరిష్కారం",
    available24x7: "24/7 అందుబాటులో",
    visualCropAssessment: "దృశ్య పంట అంచనా",
    detailedExplanations: "వివరణాత్మక వివరణలు",
    screenSharingSupport: "స్క్రీన్ షేరింగ్ మద్దతు",
    sharePhotosDocuments: "ఫోటోలు మరియు పత్రాలను పంచుకోండి",
    writtenRecommendations: "వ్రాతపూర్వక సిఫార్సులు",
    flexibleTiming: "సరళమైన సమయం",

    // Community
    farmerCommunity: "రైతు కమ్యూనిటీ",
    communityDesc: "తోటి రైతులతో కనెక్ట్ అవ్వండి, అనుభవాలను పంచుకోండి మరియు కమ్యూనిటీ యొక్క సామూహిక జ్ఞానం నుండి నేర్చుకోండి।",
    newDiscussion: "కొత్త చర్చ",
    recentDiscussions: "ఇటీవలి చర్చలు",
    categories: "వర్గాలు",
    topContributors: "అగ్ర సహకారులు",
    communityStats: "కమ్యూనిటీ గణాంకాలు",
    totalMembers: "మొత్తం సభ్యులు",
    activeDiscussions: "క్రియాశీల చర్చలు",
    questionsAnswered: "సమాధానం ఇచ్చిన ప్రశ్నలు",
    onlineNow: "ఇప్పుడు ఆన్‌లైన్‌లో",

    // News
    agriculturalNews: "వ్యవసాయ వార్తలు",
    newsDesc: "తాజా వార్తలు, వాతావరణ హెచ్చరికలు, మార్కెట్ ట్రెండ్‌లు మరియు వ్యవసాయ అభివృద్ధితో అప్‌డేట్‌గా ఉండండి।",
    allNews: "అన్ని వార్తలు",
    weatherAlerts: "వాతావరణ హెచ్చరికలు",
    marketUpdates: "మార్కెట్ అప్‌డేట్‌లు",
    governmentPolicy: "ప్రభుత్వ విధానం",
    technology: "సాంకేతికత",
    research: "పరిశోధన",
    readMore: "మరింత చదవండి",
    weatherAlert: "వాతావరణ హెచ్చరిక",
    heavyRainfallWarning: "భారీ వర్షపాతం హెచ్చరిక",
    stayUpdated: "అప్‌డేట్‌గా ఉండండి",
    subscribeNewsletter: "న్యూస్‌లెటర్‌కు సబ్‌స్క్రైబ్ చేయండి",

    // Help & Support
    helpSupportTitle: "సహాయం మరియు మద్దతు",
    helpDesc: "సాధారణ ప్రశ్నలకు సమాధానాలను కనుగొనండి, వనరులను యాక్సెస్ చేయండి మరియు Project Kisan ఉపయోగించడానికి మద్దతు పొందండి।",
    faq: "తరచుగా అడిగే ప్రశ్నలు",
    contactSupport: "మద్దతును సంప్రదించండి",
    getHelp: "సహాయం పొందండి",
    phoneSupport: "ఫోన్ మద్దతు",
    emailSupport: "ఇమెయిల్ మద్దతు",
    liveChat: "లైవ్ చాట్",
    helpResources: "సహాయ వనరులు",
    gettingStartedGuide: "ప్రారంభ గైడ్",
    videoTutorials: "వీడియో ట్యుటోరియల్స్",
    featureDocumentation: "ఫీచర్ డాక్యుమెంటేషన్",
    bestPractices: "ఉత్తమ అభ్యాసాలు",
    systemStatus: "సిస్టమ్ స్థితి",
    operational: "కార్యాచరణ",
    maintenance: "నిర్వహణ",

    // Settings
    appearance: "రూపం",
    theme: "థీమ్",
    chooseTheme: "మీ ఇష్టమైన థీమ్‌ను ఎంచుకోండి",
    light: "లేత",
    dark: "ముదురు",
    system: "సిస్టమ్",
    languageRegion: "భాష మరియు ప్రాంతం",
    language: "భాష",
    chooseLanguage: "మీ ఇష్టమైన భాషను ఎంచుకోండి",
    region: "ప్రాంతం",
    setRegion: "మీ వ్యవసాయ ప్రాంతాన్ని సెట్ చేయండి",
    weatherAlertsSettings: "వాతావరణ హెచ్చరికలు",
    weatherAlertsDesc: "వాతావరణ మార్పుల గురించి తెలియజేయండి",
    marketPriceUpdates: "మార్కెట్ ధర అప్‌డేట్‌లు",
    marketPriceDesc: "మార్కెట్ ధర నోటిఫికేషన్‌లను పొందండి",
    schemeAlerts: "ప్రభుత్వ పథక హెచ్చరికలు",
    schemeAlertsDesc: "కొత్త పథకాలపై అప్‌డేట్‌గా ఉండండి",
    diseaseWarnings: "పంట వ్యాధి హెచ్చరికలు",
    diseaseWarningsDesc: "మీ ప్రాంతంలో పంట వ్యాధుల గురించి హెచ్చరికలను పొందండి",
    voiceResponse: "వాయిస్ ప్రతిస్పందన",
    voiceResponseDesc: "వాయిస్ ప్రతిస్పందనలను ప్రారంభించండి",
    voiceSpeed: "వాయిస్ వేగం",
    voiceSpeedDesc: "వాయిస్ ప్రతిస్పందన వేగాన్ని సర్దుబాటు చేయండి",
    slow: "నెమ్మది",
    normal: "సాధారణ",
    fast: "వేగం",
    privacyData: "గోప్యత మరియు డేటా",
    dataCollection: "డేటా సేకరణ",
    dataCollectionDesc: "మెరుగైన సిఫార్సుల కోసం డేటా సేకరణను అనుమతించండి",
    locationServices: "స్థాన సేవలు",
    locationServicesDesc: "వాతావరణ మరియు మార్కెట్ డేటా కోసం స్థానాన్ని ఉపయోగించండి",
    saveSettings: "సెట్టింగ్‌లను సేవ్ చేయండి",

    // Profile
    farmSizeProfile: "వ్యవసాయ పరిమాణం",
    experience: "అనుభవం",
    primaryCrops: "ప్రాథమిక పంటలు",
    contactInformation: "సంప్రదింపు సమాచారం",
    about: "గురించి",
    saveChanges: "మార్పులను సేవ్ చేయండి",

    // Status and Actions
    active: "క్రియాశీల",
    applied: "దరఖాస్తు చేసిన",
    completed: "పూర్తయిన",
    healthy: "ఆరోగ్యకరమైన",
    treated: "చికిత్స చేసిన",
    inProgress: "పురోగతిలో",
    sellNow: "ఇప్పుడు అమ్మండి",
    hold: "పట్టుకోండి",
    monitor: "పర్యవేక్షించండి",
    goodToSell: "అమ్మడానికి మంచిది",

    // Crops and Markets
    tomato: "టమోటా",
    onion: "ఉల్లిపాయ",
    potato: "బంగాళాదుంప",
    wheat: "గోధుమ",
    rice: "వరి",
    cotton: "పత్తి",
    sugarcane: "చెరకు",
    maize: "మొక్కజొన్న",
    soybean: "సోయాబీన్",
    groundnut: "వేరుశనగ",

    // Severity Levels
    low: "తక్కువ",
    medium: "మధ్యస్థ",
    high: "అధిక",
    none: "ఏదీ లేదు",

    // Time
    today: "ఈరోజు",
    yesterday: "నిన్న",
    hoursAgo: "గంటల క్రితం",
    daysAgo: "రోజుల క్రితం",
    weeksAgo: "వారాల క్రితం",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("english")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
